name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: assignment_test
      id: assignment_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: assignment_test
        setup-command: gpgtar -d -C . --gpg-args="--passphrase=RareTackingGoofyExorcism
          --batch" .github/autograder.gpg && make build
        command: make -k all
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ASSIGNMENT_TEST_RESULTS: "${{steps.assignment_test.outputs.result}}"
      with:
        runners: assignment_test
